app = "sms-webhook"
primary_region = "ord"

[http_service]
  internal_port = 8080
  force_https = true
  auto_start_machines = true
  auto_stop_machines = false
  min_machines_running = 1
  processes = ["app"]

# Health check so smoke tests pass quickly
[[http_service.checks]]
  interval = "10s"
  timeout = "2s"
  grace_period = "20s"
  method = "GET"
  path = "/health"
  protocol = "http"
